export const replacements: { [key: string]: any } = {
  Atag: "AudioTag",
  SampleFmt: "SampleFormat",
  Absf: "AudioBitStreamFilters",
  Apre: "AudioPreset",
  Aframes: "AudioFrames",
  Aq: "AudioQuality",
  Ar: "AudioRate",
  Ac: "AudioChannels",
  An: "DisableAudio",
  Acodec: "AudioCodec",
  Vol: "Volume",
  Af: "AudioFilters",
  Dump: "DumpInputPackets",
  Hex: "DumpInputPacketPayloads",
  Vsync: "VideoSyncMethod",
  Async: "AudioSyncMethod",
  AdriftThreshold: "AudioDriftThreshold",
  Copyts: "CopyTimestamps",
  StartAtZero: "ShiftInputTimestampsToStartAtZero",
  Copytb: "CopyInputTimeBase",
  DtsDeltaThreshold: "TimestampDiscontinuityDeltaThreshold",
  DtsErrorThreshold: "TimestampErrorThreshold",
  Xerror: "ExitOnError",
  DebugTs: "DebugTimestamps",
  Sameq: "SameQ",
  Psnr: "PSNR",
  Vstats: "DumpVideoCodingStats",
  VstatsFile: "VideoCodingStatsFile",
  VstatsVersion: "VideoCodingStatsVersion",
  Qphist: "QpHistogram",
  Vc: "VideoChannel",
  Tvstd: "TVStandard",
  InitHwDevice: "InitializeHardwareDevice",
  FilterHwDevice: "HardwareDeviceForFiltering",
  Loglevel: "LogLevel",
  V: "Verbosity",
  MaxAlloc: "MaximumAllocatedBlockSize",
  Y: "OverwriteOutputFiles",
  N: "NeverOverwriteOutputFiles",
  MaxErrorRate: "MaximumErrorRate",
  "-h": "BasicHelp",
  "-h long": "MoreHelp",
  "args: -h long": [],
  "-h full": "FullHelp",
  "args: -h full": [],
  "-h type=name": ["type", "name"],
  L: "License",
  "-h topic": "HelpForTopic",
  "-? topic": "HelpForTopic",
  "args: -? topic": ["topic"],
  "-help topic": "HelpForTopic",
  "--help topic": "HelpForTopic",
  BuildConf: "BuildConfiguration",
  Bsfs: "BitStreamFilters",
  PixFmts: "PixelFormats",
  SampleFmts: "AudioSampleFormats",
  Hwaccels: "HardwareAccelerationMethods",
  "args: -map [-]input_file_id[:stream_specifier][,sync_file_id[:stream_s": [
    "mapping",
  ],
  MapChannel: "MapAudioChannel",
  AccurateSeek: "AccurateSeekingEnabled",
  Itsoffset: "InputTimestampOffset",
  Itsscale: "InputTimestampScale",
  Dframes: "OutputDataFramesCount",
  Re: "ReadInputAtNativeFrameRate",
  Copyinkf: "CopyInitialNonKeyFrames",
  Copypriorss: "ShouldCopyFramesBeforeStartTime",
  fourccTag: "tag",
  number: "num",
  Q: "VideoQualityScale",
  Qscale: "VideoQualityScale",
  Attach: "AttachFileToOutput",
  DumpAttachment: "ExtractAttachmentFromInput",
  StreamLoop: "InputLoopCount",
  "args: -stream_loop loop count": ["count"],
  "args: -thread_queue_size": ["size"],
  Muxdelay: "MaxDemuxDecodeDelay",
  Muxpreload: "InitialDemuxDecodeDelay",
  TimeBase: "OutputTimeBase",
  EncTimeBase: "EncoderTimeBase",
  Bsf: "BitStreamFilters",
  Fpre: "PresetFile",
  MaxMuxingQueueSize: "MaxBufferedPacketsDuringStreamInitialization",
  Dcodec: "DataCodec",
  F: "Format",
  C: "Codec",
  Pre: "Preset",
  T: "DurationToTranscode",
  To: "StopTranscodingAt",
  Fs: "FileSizeLimit",
  Ss: "StartTimeSeekOffset",
  Sseof: "StartTimeSeekOffsetRelativeToEOF",
  TimestampSeekingEnabled: "SeekTimestamp",
  Timestamp: "RecordingTimestamp",
  "args: -metadata string=string": ["key", "value"],
  Target: "TargetFileType",
  Apad: "AudioPad",
  Frames: "FramesToOutput",
  Filter: "FilterGraph",
  FilterScript: "FilterGraphScriptFile",
  ReinitFilter: "ReInitializeFilterGraphOnInputChange",
  S: "Size",
  Sn: "DisableSubtitles",
  Scodec: "SubtitlesCodec",
  Stag: "SubtitlesTag",
  FixSubDuration: "FixSubtitlesDuration",
  Spre: "SubtitlesPreset",
  PixFmt: "PixelFormat",
  RcOverride: "RateControlOverride",
  Passlogfile: "MultiPassLogFileNamePrefix",
  Vtag: "VideoTag",
  Streamid: "StreamId",
  Hwaccel: "UseHardwareAcceleratedDecoding",
  HwaccelDevice: "HardwareAccelerationDevice",
  hwaccelOutputFormat: "HardwareAcceleratedDecodingOutputFormat",
  Vbsf: "VideoBitStreamFilters",
  Vpre: "VideoPreset",
  Vframes: "VideoFrames",
  R: "FrameRate",
  Aspect: "AspectRatio",
  Vn: "DisableVideo",
  Vcodec: "VideoCodec",
  Timecode: "InitialTimecode",
  Vf: "VideoFilters",
  Ab: "AudioBitRate",
  B: "BitRate",
  Dn: "DisableData",
};
